/*******************************************************************************
 * This file is part of Termitaria, a project management tool 
 *  Copyright (C) 2008-2013 CodeSphere S.R.L., www.codesphere.ro
 *   
 *  Termitaria is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License 
 *  as published by the Free Software Foundation; either version 3 of 
 *  the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License 
 *  along with Termitaria. If not, see  <http://www.gnu.org/licenses/> .
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 04:18:24 PM EEST 
//


package ro.cs.om.ws.server.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.cs.dmc.ws.client.om.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndpointException_QNAME = new QName("http://localhost:8080/OM/services/schemas/messages", "OMEndpointExceptionBean");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.cs.ir.ws.client.om.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WidgetUserAuthenticationRequest }
     * 
     */
    public WidgetUserAuthenticationRequest createWidgetUserAuthenticationRequest() {
        return new WidgetUserAuthenticationRequest();
    }
    
    /**
     * Create an instance of {@link WidgetUserAuthenticationResponse }
     * 
     */
    public WidgetUserAuthenticationResponse createWidgetUserAuthenticationResponse() {
        return new WidgetUserAuthenticationResponse();
    }
    
    
    /**
     * Create an instance of {@link GetOrganisationSimpleResponse }
     * 
     */
    public GetOrganisationSimpleResponse createGetOrganisationSimpleResponse() {
        return new GetOrganisationSimpleResponse();
    }

    /**
     * Create an instance of {@link GetOrganisationSimpleRequest }
     * 
     */
    public GetOrganisationSimpleRequest createGetOrganisationSimpleRequest() {
        return new GetOrganisationSimpleRequest();
    }

    /**
     * Create an instance of {@link GetLogoRequest }
     * 
     */
    public GetLogoRequest createGetLogoRequest() {
        return new GetLogoRequest();
    }
    
    /**
     * Create an instance of {@link GetLogoResponse }
     * 
     */
    public GetLogoResponse createGetLogoResponse() {
        return new GetLogoResponse();
    }
    
    /**
     * Create an instance of {@link OrganisationSimple }
     * 
     */
    public OrganisationSimple createOrganisationSimple() {
        return new OrganisationSimple();
    }
    
    /**
     * Create an instance of {@link GetUsersSimpleResponse }
     * 
     */
    public GetUsersSimpleResponse createGetUsersSimpleResponse() {
        return new GetUsersSimpleResponse();
    }

    /**
     * Create an instance of {@link GetUsersSimpleRequest }
     * 
     */
    public GetUsersSimpleRequest createGetUsersSimpleRequest() {
        return new GetUsersSimpleRequest();
    }

    /**
     * Create an instance of {@link GetDeactivatedUsersSimpleRequest }
     * 
     
    public GetDeactivatedUsersSimpleRequest createGetDeactivatedUsersSimpleRequest() {
        return new GetDeactivatedUsersSimpleRequest();
    }
    */
    /**
     * Create an instance of {@link GetFreeDaysRequest }
     * 
     */
    public GetFreeDaysRequest createGetFreeDaysRequest() {
        return new GetFreeDaysRequest();
    }
    
    /**
     * Create an instance of {@link GetFreeDaysResponse( }
     * 
     */
    public GetFreeDaysResponse createGetFreeDaysResponse() {
        return new GetFreeDaysResponse();
    }
    
    /**
     * Create an instance of {@link GetOrganisationsByModuleRequest }
     * 
     */
    public GetOrganisationsByModuleRequest createGetOrganisationsByModuleRequest() {
        return new GetOrganisationsByModuleRequest();
    }
    
    /**
     * Create an instance of {@link GetOrganisationsByModuleResponse }
     * 
     */
    public GetOrganisationsByModuleResponse createGetOrganisationsByModuleResponse() {
        return new GetOrganisationsByModuleResponse();
    }
    /**
     * Create an instance of {@link GetUserAuthBySecurityTokenResponse }
     * 
     */
    public GetUserAuthBySecurityTokenResponse createGetUserAuthBySecurityTokenResponse() {
        return new GetUserAuthBySecurityTokenResponse();
    }
    
    /**
     * Create an instance of {@link GetUserAuthBySecurityTokenRequest }
     * 
     */
    public GetUserAuthBySecurityTokenRequest createGetUserAuthBySecurityTokenRequest() {
        return new GetUserAuthBySecurityTokenRequest();
    }
    
    
    /**
     * Create an instance of {@link GetUsersAndGroupsByOrganizationResponse }
     * 
     */
    public GetUsersAndGroupsByOrganizationResponse createGetUsersAndGroupsByOrganizationResponse() {
        return new GetUsersAndGroupsByOrganizationResponse();
    }

    /**
     * Create an instance of {@link GetUsersAndGroupsByOrganizationRequest }
     * 
     */
    public GetUsersAndGroupsByOrganizationRequest createGetUsersAndGroupsByOrganizationRequest() {
        return new GetUsersAndGroupsByOrganizationRequest();
    }
    
    /**
     * Create an instance of {@link GetDeletedUsersAndGroupsByOrganizationRequest }
     * 
     */
    public GetDeletedUsersAndGroupsByOrganizationRequest createGetDeletedUsersAndGroupsByOrganizationRequest() {
        return new GetDeletedUsersAndGroupsByOrganizationRequest();
    }
    /**
     * Create an instance of {@link GetAllOrganisationsResponse }
     * 
     */
    public GetAllOrganisationsResponse createGetAllOrganisationsResponse() {
        return new GetAllOrganisationsResponse();
    }

    /**
     * Create an instance of {@link GetAllOrganisationsRequest }
     * 
     */
    public GetAllOrganisationsRequest createGetAllOrganisationsRequest() {
        return new GetAllOrganisationsRequest();
    }

    /**
     * Create an instance of {@link WSOrganisation }
     * 
     */
    public WSOrganisation createWSOrganisation() {
        return new WSOrganisation();
    }
    
    /**
     * Create an instance of {@link OrganisationHasAuditModuleRequest }
     * 
     */
    public OrganisationHasAuditModuleRequest createOrganisationHasAuditModuleRequest() {
        return new OrganisationHasAuditModuleRequest();
    }
    
    /**
     * Create an instance of {@link OrganisationHasAuditModuleResponse }
     * 
     */
    public OrganisationHasAuditModuleResponse createOrganisationHasAuditModuleResponse() {
        return new OrganisationHasAuditModuleResponse();
    }
    
    /**
     * Create an instance of {@link OMEndpointExceptionBean }
     * 
     */
    public OMEndpointExceptionBean createEndpointException() {
        return new OMEndpointExceptionBean();
    }
    
    /**
     * Create an instance of {@link GetUsersAndGroupsByOrganizationResponse }
     * 
     */
    public GetUsersByOrganizationResponse createGetUsersByOrganizationResponse() {
        return new GetUsersByOrganizationResponse();
    }

    /**
     * Create an instance of {@link GetUsersByOrganizationRequest }
     * 
     */
    public GetUsersByOrganizationRequest createGetUsersByOrganizationRequest() {
        return new GetUsersByOrganizationRequest();
    }
    
    /**
     * Create an instance of {@link GetUsersWithRoleByOrganisationRequest}
     * 
     */
    public GetUsersWithRoleByOrganisationRequest createGetUsersWithRoleByOrganisationRequest() {
    	return new GetUsersWithRoleByOrganisationRequest();
    }
    
    /**
     * Create an instance of {@link GetUsersWithRoleByOrganisationResponse}
     * 
     */
    public GetUsersWithRoleByOrganisationResponse createGetUsersWithRoleByOrganisationResponse() {
    	return new GetUsersWithRoleByOrganisationResponse();
    }
    
    
    /**
     * Create an instance of {@link GetPersonSimpleRequest}
     * @return
     */
    public GetPersonSimpleRequest createGetPersonSimpleRequest() {
    	return new GetPersonSimpleRequest();
    }
    
    /**
     * Create an instance of {@link GetPersonSimpleResponse}
     * @return
     */
    public GetPersonSimpleResponse createGetPersonSimpleResponse() {
    	return new GetPersonSimpleResponse();
    }   
    
    /**
     * Create an instance of {@link GetUserGroupByIdRequest }
     * 
     */
    public GetUserGroupByIdRequest createGetUserGroupByIdRequest(){
    	return new GetUserGroupByIdRequest();
    }
    
    /**
     * Create an instance of {@link GetUserGroupByIdResponse }
     * 
     */
    public GetUserGroupByIdResponse createGetUserGroupByIdResponse(){
    	return new GetUserGroupByIdResponse();
    }
    
    /**
     * Create an instance of {@link GetUserGroupsByUserResponse }
     * 
     */
    public GetUserGroupsByUserResponse createGetUserGroupsByUserResponse(){
    	return new GetUserGroupsByUserResponse();
    }
    
    /**
     * Create an instance of {@link GetUserGroupsByUserRequest }
     * 
     */
    public GetUserGroupsByUserRequest createGetUserGroupsByUserRequest(){
    	return new GetUserGroupsByUserRequest();
    }
    
    /**
     * Create an instance of {@link GetUsersSimpleByGroupRequest }
     * 
     */
    public GetUsersSimpleByGroupRequest createGetUsersSimpleByGroupRequest(){
    	return new GetUsersSimpleByGroupRequest();
    }
    
    /**
     * Create an instance of {@link GetUsersSimpleByGroupResponse }
     * 
     */
    public GetUsersSimpleByGroupResponse createGetUsersSimpleByGroupResponse(){
    	return new GetUsersSimpleByGroupResponse();
    }
    
    /**
     * Create an instance of {@link GetUsersSimpleByPersonIdResponse }
     * 
     */
    public GetUsersSimpleByPersonIdResponse createGetUsersSimpleByPersonIdResponse(){
    	return new GetUsersSimpleByPersonIdResponse();
    }
    
    /**
     * Create an instance of {@link GetUsersSimpleByPersonIdRequest }
     * 
     */
    public GetUsersSimpleByPersonIdRequest createGetUsersSimpleByPersonIdRequest(){
    	return new GetUsersSimpleByPersonIdRequest();
    }
    
    /**
     * Create an instance of {@link GetPersonFromSearchRequest }
     * 
     */
    public GetPersonFromSearchRequest createGetPersonFromSearchRequest() {
        return new GetPersonFromSearchRequest();
    }
    
    /**
     * Create an instance of {@link GetPersonFromSearchResponse }
     * 
     */
    public GetPersonFromSearchResponse createGetPersonFromSearchResponse() {
        return new GetPersonFromSearchResponse();
    }  
    
    /**
     * Create an instance of {@link GetCalendarByOrganizationRequest }
     * 
     */
    public GetCalendarByOrganizationRequest createGetCalendarByOrganizationRequest() {
        return new GetCalendarByOrganizationRequest();
    }
    
    /**
     * Create an instance of {@link GetCalendarByOrganizationResponse }
     * 
     */
    public GetCalendarByOrganizationResponse createGetCalendarByOrganizationResponse() {
        return new GetCalendarByOrganizationResponse();
    }  
    
    /**
     * Create an instance of {@link GetPersonsByRoleRequest }
     * 
     */
    public GetPersonsByRoleRequest createGetPersonsByRoleRequest() {
        return new GetPersonsByRoleRequest();
    }
    
    /**
     * Create an instance of {@link GetPersonsByRoleResponse }
     * 
     */
    public GetPersonsByRoleResponse createGetPersonsByRoleResponse() {
        return new GetPersonsByRoleResponse();
    } 
    
    /**
     * Create an instance of {@link WSSearchPersonBean }
     * 
     */
    public WSSearchPersonBean createWSSearchPersonBean() {
        return new WSSearchPersonBean();
    }     

    /**
     * Create an instance of {@link OMEndpointExceptionBean }
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/OM/services/schemas/messages", name = "OMEndpointExceptionBean")
    public JAXBElement<OMEndpointExceptionBean> createEndpointException(OMEndpointExceptionBean value) {
        return new JAXBElement<OMEndpointExceptionBean>(_EndpointException_QNAME, OMEndpointExceptionBean.class, null, value);
    }
    
}
