/*******************************************************************************
 * This file is part of Termitaria, a project management tool 
 *  Copyright (C) 2008-2013 CodeSphere S.R.L., www.codesphere.ro
 *   
 *  Termitaria is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License 
 *  as published by the Free Software Foundation; either version 3 of 
 *  the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License 
 *  along with Termitaria. If not, see  <http://www.gnu.org/licenses/> .
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.28 at 05:54:47 PM EEST 
//


package ro.cs.om.ws.server.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for WSUser complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType name="WSUser">
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;all>
*         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
*         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
*       &lt;/all>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSUser", propOrder = {

})
public class WSUser {

	 @XmlElement(namespace = "http://localhost:8080/OM/services/schemas/messages")
	 protected int id;
	 @XmlElement(namespace = "http://localhost:8080/OM/services/schemas/messages", required = true)
	 protected String name;
	 @XmlElement(namespace = "http://localhost:8080/OM/services/schemas/messages", required = true)
	 protected String firstName;
	 @XmlElement(namespace = "http://localhost:8080/OM/services/schemas/messages", required = true)
	 protected String lastName; 
	 @XmlElement(namespace = "http://localhost:8080/OM/services/schemas/messages")    
	 protected boolean enabled;	
	 @XmlElement(namespace = "http://localhost:8080/OM/services/schemas/messages")    
	 protected byte status;
	 @XmlElement(namespace = "http://localhost:8080/OM/services/schemas/messages")
	 protected String email;

	 /**
	  * Gets the value of the id property.
	  * 
	  */
	 public int getId() {
	     return id;
	 }
	
	 /**
	  * Sets the value of the id property.
	  * 
	  */
	 public void setId(int value) {
	     this.id = value;
	 }
	
	 /**
	  * Gets the value of the name property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getName() {
	     return name;
	 }
	
	 /**
	  * Sets the value of the name property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setName(String value) {
	     this.name = value;
	 }
	
	 /**
	  * Gets the value of the firstName property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getFirstName() {
	     return firstName;
	 }
	
	 /**
	  * Sets the value of the firstName property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setFirstName(String value) {
	     this.firstName = value;
	 }
	
	 /**
	  * Gets the value of the lastName property.
	  * 
	  * @return
	  *     possible object is
	  *     {@link String }
	  *     
	  */
	 public String getLastName() {
	     return lastName;
	 }
	
	 /**
	  * Sets the value of the lastName property.
	  * 
	  * @param value
	  *     allowed object is
	  *     {@link String }
	  *     
	  */
	 public void setLastName(String value) {
	     this.lastName = value;
	 }
	 
	 /**
	  * Gets the value of the group property.
	  * 
	  */
	 public boolean isEnabled() {
	     return enabled;
	 }

	 /**
	  * Sets the value of the group property.
	  * 
	  */
	 public void setEnabled(boolean value) {
	     this.enabled = value;
	 }	 	
         	
	/**
	 * @return the status
	 */
	public byte getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(byte status) {
		this.status = status;
	}	

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	public String toString() {
	 	StringBuffer sb = new StringBuffer("[");
	 	sb.append(this.getClass().getSimpleName());
	 	sb.append(": ");
	 	sb.append("id = ")             .append(id)             .append(", ");
	 	sb.append("name = ")           .append(name)           .append(", ");
	 	sb.append("firstName = ")      .append(firstName)      .append(", ");
	 	sb.append("lastName = ")       .append(lastName)       .append(", ");    
	 	sb.append("status = ")         .append(status)         .append(",");
	 	sb.append("email = ")          .append(email)          .append(",");
	 	sb.append("enabled = ")        .append(enabled)        .append("]");
	 	return sb.toString();
	}
}
