/*******************************************************************************
 * This file is part of Termitaria, a project management tool 
 *  Copyright (C) 2008-2013 CodeSphere S.R.L., www.codesphere.ro
 *   
 *  Termitaria is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License 
 *  as published by the Free Software Foundation; either version 3 of 
 *  the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License 
 *  along with Termitaria. If not, see  <http://www.gnu.org/licenses/> .
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.08 at 07:04:39 PM EEST 
//


package ro.cs.logaudit.ws.client.reports.entity;

import java.util.Date;
import java.util.HashMap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AuditEventsReportParams complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuditEventsReportParams">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="startDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="endDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="event" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="resultsPerPage" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="reportTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuditEventsReportParams", propOrder = {

})
public class AuditEventsReportParams {

	public AuditEventsReportParams(){}
	/*
	 * Holds pairs Key - Value, where Key it's a property name, and value, a
	 * property value.
	 */
   	@XmlElementWrapper(name="properties", namespace = "http://localhost:8080/Reports/services/schemas/messages")
	private HashMap<String, Object> properties = new HashMap<String, Object>();
   	
	/*
	 * Holds pairs Key - Value, where Key it's a property name, and value, a
	 * property type;
	 */
	@XmlElementWrapper(name="propertiesTypes", namespace = "http://localhost:8080/Reports/services/schemas/messages")
	private HashMap<String, String> propertiesTypes = new HashMap<String, String>();

   	public HashMap<String, Object> getProperties() {
		return properties;
	}
	public void setProperties(HashMap<String, Object> properties) {
		this.properties = properties;
	}
	public HashMap<String, String> getPropertiesTypes() {
		return propertiesTypes;
	}
	public void setPropertiesTypes(HashMap<String, String> propertiesTypes) {
		this.propertiesTypes = propertiesTypes;
	}
	
	/**
	 * Sets or updates a property of this Item.
	 */
	public void setProperty(String name, String value) {
		properties.put(name, value);
		propertiesTypes.put(name, "java.lang.String");
	}

	/**
	 * Sets or updates a property of this Item.
	 */
	public void setProperty(String name, long value) {
		properties.put(name, value);
		propertiesTypes.put(name, "long");
	}

	/**
	 * Sets or updates a property of this Item.
	 */
	public void setProperty(String name, double value) {
		properties.put(name, value);
		propertiesTypes.put(name, "double");
	}

	/**
	 * Sets or updates a property of this Item.
	 */
	public void setProperty(String name, Date value) {
		properties.put(name, value);
		propertiesTypes.put(name, "java.util.Date");
	}

	/**
	 * Sets or updates a property of this Item.
	 */
	public void setProperty(String name, boolean value) {
		properties.put(name, value);
		propertiesTypes.put(name, "boolean");
	}
	
	/**
	 * Sets or updates a property of this Item.
	 */
	public void setProperty(String name, XMLGregorianCalendar value) {
		properties.put(name, value);
		propertiesTypes.put(name, "javax.xml.datatype.XMLGregorianCalendar");
	}
	
	/**
	 * Sets or updates a property of this Item.
	 */
	public void setProperty(String name, int value) {
		properties.put(name, value);
		propertiesTypes.put(name, "int");
	}
	
	/**
	 * Sets or updates a property of this Item.
	 */
	public void setProperty(String name, Integer value) {
		properties.put(name, value);
		propertiesTypes.put(name, "java.lang.Integer");
	}

}
