/*******************************************************************************
 * This file is part of Termitaria, a project management tool 
 *  Copyright (C) 2008-2013 CodeSphere S.R.L., www.codesphere.ro
 *   
 *  Termitaria is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License 
 *  as published by the Free Software Foundation; either version 3 of 
 *  the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License 
 *  along with Termitaria. If not, see  <http://www.gnu.org/licenses/> .
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 04:18:24 PM EEST 
//


package ro.cs.logaudit.ws.client.om.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.cs.dmc.ws.client.om.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndpointException_QNAME = new QName("http://localhost:8080/OM/services/schemas/messages", "OMEndpointExceptionBean");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.cs.logaudit.ws.client.om.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllOrganisationsResponse }
     * 
     */
    public GetAllOrganisationsResponse createGetAllOrganisationsResponse() {
        return new GetAllOrganisationsResponse();
    }

    /**
     * Create an instance of {@link GetAllOrganisationsRequest }
     * 
     */
    public GetAllOrganisationsRequest createGetAllOrganisationsRequest() {
        return new GetAllOrganisationsRequest();
    }

    /**
     * Create an instance of {@link WSOrganisation }
     * 
     */
    public WSOrganisation createWSOrganisation() {
        return new WSOrganisation();
    }
    
    /**
     * Create an instance of {@link GetUserAuthBySecurityTokenResponse }
     * 
     */
    public GetUserAuthBySecurityTokenResponse createGetUserAuthBySecurityTokenResponse() {
        return new GetUserAuthBySecurityTokenResponse();
    }
    
    /**
     * Create an instance of {@link GetUserAuthBySecurityTokenRequest }
     * 
     */
    public GetUserAuthBySecurityTokenRequest createGetUserAuthBySecurityTokenRequest() {
        return new GetUserAuthBySecurityTokenRequest();
    }
    
    /**
     * Create an instance of {@link GetUsersSimpleResponse }
     * 
     */
    public GetUsersSimpleResponse createGetUsersSimpleResponse() {
        return new GetUsersSimpleResponse();
    }

    /**
     * Create an instance of {@link GetUsersSimpleRequest }
     * 
     */
    public GetUsersSimpleRequest createGetUsersSimpleRequest() {
        return new GetUsersSimpleRequest();
    }
    
    /**
     * Create an instance of {@link UserSimple }
     * 
     */
    public UserSimple createUserSimple() {
        return new UserSimple();
    }
    
    
    /**
     * Create an instance of {@link OMEndpointExceptionBean }
     * 
     */
    public OMEndpointExceptionBean createEndpointException() {
        return new OMEndpointExceptionBean();
    }
    

    /**
     * Create an instance of {@link OMEndpointExceptionBean }
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/OM/services/schemas/messages", name = "OMEndpointExceptionBean")
    public JAXBElement<OMEndpointExceptionBean> createEndpointException(OMEndpointExceptionBean value) {
        return new JAXBElement<OMEndpointExceptionBean>(_EndpointException_QNAME, OMEndpointExceptionBean.class, null, value);
    }
    
}
