/*******************************************************************************
 * This file is part of Termitaria, a project management tool 
 *  Copyright (C) 2008-2013 CodeSphere S.R.L., www.codesphere.ro
 *   
 *  Termitaria is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License 
 *  as published by the Free Software Foundation; either version 3 of 
 *  the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License 
 *  along with Termitaria. If not, see  <http://www.gnu.org/licenses/> .
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.07 at 06:32:57 PM EEST 
//


package ro.cs.logaudit.ws.server.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import ro.cs.logaudit.common.IConstant;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.cs.logaudit.ws.server.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _EndpointException_QNAME = new QName(IConstant.AUDIT_WS_SERVER_NAMESPACE, "AuditEndpointExceptionBean");
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.cs.logaudit.ws.server.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuditEndpointExceptionBean }
     * 
     */
    public AuditEndpointExceptionBean createAuditEndpointExceptionBean() {
        return new AuditEndpointExceptionBean();
    }

    /**
     * Create an instance of {@link DMEEndpointExceptionBean }
     * 
     */
    @XmlElementDecl(namespace = IConstant.AUDIT_WS_SERVER_NAMESPACE, name = "AuditEndpointExceptionBean")
    public JAXBElement<AuditEndpointExceptionBean> createEndpointException(AuditEndpointExceptionBean value) {
        return new JAXBElement<AuditEndpointExceptionBean>(_EndpointException_QNAME, AuditEndpointExceptionBean.class, null, value);
    }

    /**
     * Create an instance of {@link AuditEvent }
     * 
     */
    public AuditEvent createAuditEvent() {
        return new AuditEvent();
    }

    /**
     * Create an instance of {@link AuditEventRequest }
     * 
     */
    public AuditEventRequest createAuditEventRequest() {
        return new AuditEventRequest();
    }
    
    /**
     * Create an instance of {@link AuditEventsReportDatasouceRequest }
     * 
     */
    public AuditEventsReportDatasouceRequest createAuditEventsReportDatasouceRequest() {
        return new AuditEventsReportDatasouceRequest();
    }
    
    /**
     * Create an instance of {@link AuditEventsReportGetDataCriteria }
     * 
     */
    public AuditEventsReportGetDataCriteria createAuditEventsReportGetDataCriteria() {
        return new AuditEventsReportGetDataCriteria();
    }
    
    /**
     * Create an instance of {@link AuditEventsReportDatasouceResponse }
     * 
     */
    public AuditEventsReportDatasouceResponse createAuditEventsReportDatasouceResponse() {
        return new AuditEventsReportDatasouceResponse();
    }
    
    /**
     * Create an instance of {@link WSAuditOmBean }
     * 
     */
    public WSAuditOmBean createWSAuditOmBean() {
        return new WSAuditOmBean();
    }
    
    /**
     * Create an instance of {@link WSAuditDmBean }
     * 
     */
    public WSAuditDmBean createWSAuditDmBean() {
        return new WSAuditDmBean();
    }
    
    /**
     * Create an instance of {@link WSAuditCmBean }
     * 
     */
    public WSAuditCmBean createWSAuditCmBean() {
        return new WSAuditCmBean();
    }
    
    /**
     * Create an instance of {@link WSAuditTsBean }
     * 
     */
    public WSAuditTsBean createWSAuditTsBean() {
        return new WSAuditTsBean();
    }
    
}
