/*******************************************************************************
 * This file is part of Termitaria, a project management tool 
 *  Copyright (C) 2008-2013 CodeSphere S.R.L., www.codesphere.ro
 *   
 *  Termitaria is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License 
 *  as published by the Free Software Foundation; either version 3 of 
 *  the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License 
 *  along with Termitaria. If not, see  <http://www.gnu.org/licenses/> .
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 04:18:24 PM EEST 
//


package ro.cs.cm.ws.client.ts.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import ro.cs.cm.ws.server.entity.CMEndpointExceptionBean;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.cs.cm.ws.client.ts.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndpointException_QNAME = new QName("http://localhost:8080/TS/services/schemas/messages", "CMEndpointExceptionBean");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.cs.cm.ws.client.ts.entity
     * 
     */
    public ObjectFactory() {
    } 
    
    /**
     * Create an instance of {@link CMEndpointExceptionBean }
     * 
     */
    public TSEndpointExceptionBean createEndpointException() {
        return new TSEndpointExceptionBean();
    }
    

    /**
     * Create an instance of {@link CMEndpointExceptionBean }
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/TS/services/schemas/messages", name = "CMEndpointExceptionBean")
    public JAXBElement<TSEndpointExceptionBean> createEndpointException(TSEndpointExceptionBean value) {
        return new JAXBElement<TSEndpointExceptionBean>(_EndpointException_QNAME, TSEndpointExceptionBean.class, null, value);
    }
    
    /**
       /**
     * Create an instance of {@link GetProjectIdForDeleteRequest }
     * 
     */
    public GetProjectIdForDeleteRequest createGetProjectIdRequest() {
        return new GetProjectIdForDeleteRequest();
    }       
    
    /**
     * Create an instance of {@link GetProjectIdForFinishRequest }
     * 
     */
    public GetProjectIdForFinishRequest createGetProjectIdForFinishRequest() {
        return new GetProjectIdForFinishRequest();
    }
    
    /**
     * Create an instance of {@link GetProjectIdForAbortRequest }
     * 
     */
    public GetProjectIdForAbortRequest createGetProjectIdForAbortRequest() {
        return new GetProjectIdForAbortRequest();
    }
    
    /**
     * Create an instance of {@link GetProjectIdForOpenRequest }
     * 
     */
    public GetProjectIdForOpenRequest createGetProjectIdForOpenRequest() {
        return new GetProjectIdForOpenRequest();
    }
    
    /**
     * Create an instance of {@link GetProjectIdForOpenRequest }
     * 
     */
    public GetTeamMemberIdForDeleteRequest createGetTeamMemberIdForDeleteRequest() {
        return new GetTeamMemberIdForDeleteRequest();
    }
    
    
    /**
     * Create an instance of {@link WSProjectId }
     * 
     */
    public WSProjectId createWSProjectId() {
    	return new WSProjectId();
    }
}
