/*******************************************************************************
 * This file is part of Termitaria, a project management tool 
 *  Copyright (C) 2008-2013 CodeSphere S.R.L., www.codesphere.ro
 *   
 *  Termitaria is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License 
 *  as published by the Free Software Foundation; either version 3 of 
 *  the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License 
 *  along with Termitaria. If not, see  <http://www.gnu.org/licenses/> .
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.27 at 04:18:24 PM EEST 
//


package ro.cs.cm.ws.server.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import ro.cs.cm.ws.client.om.entity.UserSimple;





/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.cs.dmc.ws.client.om.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EndpointException_QNAME = new QName("http://localhost:8080/CM/services/schemas/messages", "CMEndpointExceptionBean");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.cs.ir.ws.client.om.entity
     * 
     */
    public ObjectFactory() {
    }

    
    /**
     * Create an instance of {@link CMEndpointExceptionBean }
     * 
     */
    public CMEndpointExceptionBean createEndpointException() {
        return new CMEndpointExceptionBean();
    }
    
    /**
     * Create an instance of {@link WSClient }
     * 
     */
    public WSClient createWSClient() {
        return new WSClient();
    }
    
    /**
     * Create an instance of {@link WSProject }
     * 
     */
    public UserSimple createUserSimple() {
        return new UserSimple();
    }
    
    /**
     * Create an instance of {@link WSProject }
     * 
     */
    public WSProject createWSProject() {
        return new WSProject();
    }
    
    /**
     * Create an instance of {@link WSProjectTeam }
     * 
     */
    public WSProjectTeam createWSProjectTeam() {
        return new WSProjectTeam();
    }
    
    /**
     * Create an instance of {@link WSTeamMember }
     * 
     */
    public WSTeamMember createWSTeamMember() {
        return new WSTeamMember();
    }
    
    /**
     * Create an instance of {@link GetAllProjectsRequest }
     * 
     */
    public GetAllProjectsRequest createGetAllProjectsRequest() {
        return new GetAllProjectsRequest();
    }
    
    /**
     * Create an instance of {@link GetAllProjectsResponse }
     * 
     */
    public GetAllProjectsResponse createGetAllProjectsResponse() {
        return new GetAllProjectsResponse();
    }
    
    /**
     * Create an instance of {@link GetProjectsByManagerRequest }
     * 
     */
    public GetProjectsByManagerRequest createGetProjectsByManagerRequest() {
        return new GetProjectsByManagerRequest();
    }
    
    /**
     * Create an instance of {@link GetProjectsByManagerResponse }
     * 
     */
    public GetProjectsByManagerResponse createGetProjectsByManagerResponse() {
        return new GetProjectsByManagerResponse();
    }
    
    /**
     * Create an instance of {@link GetProjectsAndTeamMembersByPersonResponse }
     * 
     */
    public GetProjectsAndTeamMembersByPersonResponse createGetProjectsAndTeamMembersByPersonResponse() {
        return new GetProjectsAndTeamMembersByPersonResponse();
    }
    
    /**
     * Create an instance of {@link GetProjectsAndTeamMembersByPersonRequest }
     * 
     */
    public GetProjectsAndTeamMembersByPersonRequest createGetProjectsAndTeamMembersByPersonRequest() {
        return new GetProjectsAndTeamMembersByPersonRequest();
    }
    
    /**
     * Create an instance of {@link GetClientsForProjectResponse }
     * 
     */
    public GetClientsForProjectResponse createGetClientsForProjectResponse() {
        return new GetClientsForProjectResponse();
    }
    
    /**
     * Create an instance of {@link GetClientsForProjectRequest }
     * 
     */
    public GetClientsForProjectRequest createGetClientsForProjectRequest() {
        return new GetClientsForProjectRequest();
    }
    
    /**
     * Create an instance of {@link GetProjectByProjectIdRequest }
     * 
     */
    public GetProjectByProjectIdRequest createGetProjectByProjectIdRequest() {
        return new GetProjectByProjectIdRequest();
    }
    
    /**
     * Create an instance of {@link GetProjectByProjectIdResponse }
     * 
     */
    public GetProjectByProjectIdResponse createGetProjectByProjectIdResponse() {
        return new GetProjectByProjectIdResponse();
    }
    
    /**
     * Create an instance of {@link GetTeamMemberFromSearchRequest }
     * 
     */
    public GetTeamMemberFromSearchRequest createGetTeamMemberFromSearchRequest() {
        return new GetTeamMemberFromSearchRequest();
    }
    
    /**
     * Create an instance of {@link GetTeamMemberFromSearchResponse }
     * 
     */
    public GetTeamMemberFromSearchResponse createGetTeamMemberFromSearchResponse() {
        return new GetTeamMemberFromSearchResponse();
    }
    
    /**
     * Create an instance of {@link GetTeamMembersByMemberIdsRequest }
     * 
     */
    public GetTeamMembersByMemberIdsRequest createGetTeamMembersByMemberIdsRequest() {
        return new GetTeamMembersByMemberIdsRequest();
    }
    
    /**
     * Create an instance of {@link GetTeamMembersByMemberIdsResponse }
     * 
     */
    public GetTeamMembersByMemberIdsResponse createGetTeamMembersByMemberIdsResponse() {
        return new GetTeamMembersByMemberIdsResponse();
    }
    
    /**
     * Create an instance of {@link GetTeamMembersByProjectIdsRequest }
     * 
     */
    public GetTeamMembersByProjectIdsRequest createGetTeamMembersByProjectIdsRequest() {
        return new GetTeamMembersByProjectIdsRequest();
    }
    
    /**
     * Create an instance of {@link GetTeamMembersByProjectIdsResponse }
     * 
     */
    public GetTeamMembersByProjectIdsResponse createGetTeamMembersByProjectIdsResponse() {
        return new GetTeamMembersByProjectIdsResponse();
    }
    
    /**
     * Create an instance of {@link GetProjectsSimpleByProjectIdsResponse }
     * 
     */
    public GetProjectsSimpleByProjectIdsResponse createGetProjectsSimpleByProjectIdsResponse() {
        return new GetProjectsSimpleByProjectIdsResponse();
    }
    
    /**
     * Create an instance of {@link GetProjectsSimpleByProjectIdsRequest }
     * 
     */
    public GetProjectsSimpleByProjectIdsRequest createGetProjectsSimpleByProjectIdsRequest() {
        return new GetProjectsSimpleByProjectIdsRequest();
    }
    
    /**
     * Create an instance of {@link WSSearchTeamMemberBean }
     * 
     */
    public WSSearchTeamMemberBean createWSSearchTeamMemberBean() {
        return new WSSearchTeamMemberBean();
    }
    
    /**
     * Create an instance of {@link CMEndpointExceptionBean }
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/CM/services/schemas/messages", name = "CMEndpointExceptionBean")
    public JAXBElement<CMEndpointExceptionBean> createEndpointException(CMEndpointExceptionBean value) {
        return new JAXBElement<CMEndpointExceptionBean>(_EndpointException_QNAME, CMEndpointExceptionBean.class, null, value);
    }
    
}
