/*******************************************************************************
 * This file is part of Termitaria, a project management tool 
 *  Copyright (C) 2008-2013 CodeSphere S.R.L., www.codesphere.ro
 *   
 *  Termitaria is free software; you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License 
 *  as published by the Free Software Foundation; either version 3 of 
 *  the License, or (at your option) any later version.
 *  
 *  This program is distributed in the hope that it will be useful, 
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of 
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 *  GNU Affero General Public License for more details.
 *  
 *  You should have received a copy of the GNU Affero General Public License 
 *  along with Termitaria. If not, see  <http://www.gnu.org/licenses/> .
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.01 at 12:11:46 PM EEST 
//


package ro.cs.om.ws.client.dme.entity;

import java.util.ArrayList;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ro.cs.dme.ws.server.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	public final static String NAMESPACE = "http://localhost:8080/DMEngine/services/schemas/messages";
	
	private final static QName _DeleteWorkspace_QNAME = new QName(NAMESPACE, "DeleteWorkspace");
	private final static QName _DeleteWorkspaces_QNAME = new QName(NAMESPACE, "DeleteWorkspaces");
	private final static QName _DeleteWorkspaceResponse_QNAME = new QName(NAMESPACE, "DeleteWorkspaceResponse");
    private final static QName _EndpointException_QNAME = new QName(NAMESPACE, "DMEEndpointExceptionBean");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ro.cs.dme.ws.server.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DMEEndpointExceptionBean }
     * 
     */
    public DMEEndpointExceptionBean createEndpointException() {
        return new DMEEndpointExceptionBean();
    }

    /**
     * Create an instance of {@link DMEEndpointExceptionBean }
     * 
     */
    @XmlElementDecl(namespace = "http://localhost:8080/DMEngine/services/schemas/messages", name = "DMEEndpointExceptionBean")
    public JAXBElement<DMEEndpointExceptionBean> createEndpointException(DMEEndpointExceptionBean value) {
        return new JAXBElement<DMEEndpointExceptionBean>(_EndpointException_QNAME, DMEEndpointExceptionBean.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = NAMESPACE, name = "DeleteWorkspace")
    public JAXBElement<String> createDeleteWorkpaceRequest(String value) {
        return new JAXBElement<String>(_DeleteWorkspace_QNAME, String.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = NAMESPACE, name = "DeleteWorkspaces")
    public JAXBElement<DMWorkspaces> createDeleteWorkpacesRequest(DMWorkspaces value) {
        return new JAXBElement<DMWorkspaces>(_DeleteWorkspaces_QNAME, DMWorkspaces.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = NAMESPACE, name = "DeleteWorkspaceResponse")
    public JAXBElement<Boolean> createDeleteWorkpaceResponse(Boolean value) {
        return new JAXBElement<Boolean>(_DeleteWorkspaceResponse_QNAME, Boolean.class, null, value);
    }
    
}
